title: "Peter and Erika's Wedding"
description: "..."
baseurl: ""
url: "http://wedding.peteranderika.info"

title_image_path: "/images/header-photo.jpg"
post_limit: 10
# Footer
footer_text: "with <i class=\"fa fa-heart\"></i> from Peter and Erika"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
exclude: [vendor]
